version: "3.9"
services:
    websvc:
        container_name: "newsTrends.with_mariadb_websvc.v1"
        build: .
        ports:
            - "5000:5000"
        depends_on:
            - db
        links:
            - db
        restart: 'always'
        env_file: .env
        environment:
            SVC_HOST: 0.0.0.0
            DB_NAME: "${DB_NAME}"
            DB_USER: "${DB_USER}"
            DB_PASSWORD: "${DB_PASSWORD}"
            DB_SERVER: db
    db:
        container_name: "newsTrends.with_mariadb_db.v1"
        image: "mariadb:latest"
        ports:
            - "3306:3306"
        restart: 'always'
        environment:
            MARIADB_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
        volumes:
            - ${WEBAPP_STORAGE_HOME}./data:/docker-entrypoint-initdb.d
